services:
  landing-page:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: global-core-technologies-landing:local
    container_name: gct-landing
    ports:
      - "${PORT_BINDING:-3000:3000}"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: ${PORT:-3000}
    restart: unless-stopped
    networks:
      nginx_red_compartida:
        ipv4_address: ${IPV4_ADDRESS}

  landing-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: global-core-technologies-landing-api:local
    container_name: gct-landing-api
    env_file:
      - ./backend/.env
    environment:
      APP_ENV: production
    restart: unless-stopped
    networks:
      nginx_red_compartida:
        ipv4_address: ${IPV4_ADDRESS_API}

networks:
  nginx_red_compartida:
    external: true
